title: BCTCS 2023
email: email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The British Colloquium for Theoretical Computer Science (BCTCS) is an annual event for UK-based researchers in theoretical computer science and will be held in
  Glasgow in 2023.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bctcs2023.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: glasgowcs

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
